"use client"
import React, { useState, useTransition } from "react"
import { generateReportDraft } from "@/ai/flows/generate-report-draft"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useToast } from "@/hooks/use-toast"
import { Bot, Clipboard, Loader2 } from "lucide-react"

export function GenerateReportForm() {
  const [isPending, startTransition] = useTransition()
  const [notes, setNotes] = useState("")
  const [draft, setDraft] = useState("")
  const { toast } = useToast()

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!notes) {
      toast({
        title: "Error",
        description: "Appointment notes cannot be empty.",
        variant: "destructive",
      })
      return
    }
    setDraft("")
    startTransition(async () => {
      const result = await generateReportDraft({ appointmentNotes: notes })
      if (result.reportDraft) {
        setDraft(result.reportDraft)
        toast({
          title: "Success",
          description: "Report draft generated successfully.",
        })
      } else {
        toast({
          title: "Error",
          description: "Failed to generate report draft. Please try again.",
          variant: "destructive",
        })
      }
    })
  }
  
  const handleCopy = () => {
    navigator.clipboard.writeText(draft);
    toast({
      title: "Copied!",
      description: "Report draft copied to clipboard.",
    });
  }

  return (
    <form onSubmit={handleSubmit}>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Appointment Notes</CardTitle>
            <CardDescription>Enter the notes from the patient's appointment.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid w-full gap-1.5">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                placeholder="Type or paste appointment notes here..."
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                rows={15}
              />
            </div>
          </CardContent>
          <CardFooter>
            <Button type="submit" disabled={isPending}>
              {isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                 <>
                  <Bot className="mr-2 h-4 w-4" />
                  Generate Draft
                </>
              )}
            </Button>
          </CardFooter>
        </Card>
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>AI-Generated Report Draft</CardTitle>
            <CardDescription>Review the draft generated by AI, including ICD codes.</CardDescription>
          </CardHeader>
          <CardContent className="flex-grow">
            {isPending ? (
               <div className="flex items-center justify-center h-full">
                  <div className="flex flex-col items-center gap-2 text-muted-foreground">
                    <Loader2 className="h-8 w-8 animate-spin" />
                    <p>Generating report...</p>
                  </div>
                </div>
            ) : (
            <div className="relative">
              <Textarea
                placeholder="Generated report will appear here..."
                value={draft}
                readOnly
                rows={15}
                className="bg-muted"
              />
              {draft && (
                <Button
                  variant="ghost"
                  size="icon"
                  className="absolute top-2 right-2"
                  onClick={handleCopy}
                  type="button"
                >
                  <Clipboard className="h-4 w-4" />
                </Button>
              )}
            </div>
            )}
          </CardContent>
        </Card>
      </div>
    </form>
  )
}
